### ISSUE TITLE
PLEASE MOOSYU

### ISSUE THREAD

**Issue by nvjynxALT** [Moosyu/moosyu.github.io#2]
I've tested this on multiple Chromebooks and the fnf mods work for school and personal ones very smoothly please add more mods to your github.io page this will be very helpful for plenty of people.

**Comment by UwU-Zi** [comment]
excuse me Moosyu can you add the stickman mod with wrath soul plz and imposter V3 mod for the fnf part plz that's all im asking for thank you ☺

**Comment by Moosyu** [comment]
hmmmmmmmmmmmmmmmmm

**Comment by Moosyu** [comment]
> 

Ok I am working on adding the imposter v3 but I'm uncertain about the others.
