### ISSUE TITLE
Not An Issue,  A Request

### ISSUE THREAD

**Issue by SchoolPurposes07** [Moosyu/moosyu.github.io#3]
I was wondering if it is possible to have discord within a website, if it is possible (AND you have the time) could you add it to your website.

Btw I'm fine with whatever you decide, It is your website anyways!

**Comment by Moosyu** [comment]
I don't know how to do that but I have seen emulators of chrome online that have the ability to make things unblocked. Sorry that I can't help very much but I hope it at least is slightly useful.
