### ISSUE TITLE
Vanilla FNF Issue

### ISSUE THREAD

**Issue by SchoolPurposes07** [Moosyu/moosyu.github.io#4]
The issue I'm having is with the main starting screen with girlfriend on the speakers and the logo, when I press enter, the "Press enter to begin text" just flashes and I don't progress to the main menu.

I've tried this on 2 different wifi routers and neither of them work, its still entirely possible its on my end.

**Comment by Moosyu** [comment]
Sorry but I'm not working on FNF anymore
